source 'https://rubygems.org'

ruby '2.3.1'
gem 'rails'
gem 'dotenv-rails'
gem 'pg',        group: :production
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'dalli'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/rails/turbolinks.git'
gem 'jbuilder'
gem 'sdoc',          group: :doc
gem 'cancan'
gem 'foundation-rails', '=5.5.3.2'
gem 'thin'
gem 'faye'
gem 'rspec'
gem 'ruby-ntlm'
group :development do
  gem 'brakeman', :require => false
  #gem 'rack-mini-profiler'
  gem 'traceroute'
  gem 'spring'
  gem 'sqlite3'
  gem 'bullet'
end
gem 'gritter'
gem 'bcrypt'
gem 'font-awesome-rails'
gem 'wysiwyg-rails', '=2.3.0'
gem 'paperclip'
gem 'jquery-turbolinks'
gem 'will_paginate'
gem 'rails-perftest'
gem 'ruby-prof'
gem 'pg_search'
gem 'responders'
gem 'pry'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'newrelic_rpm'
